spring:
  datasource:
#        url: jdbc:mysql://localhost:3306/baissekf11
#        username: root
#        password: root
#        driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dev1?characterEncoding=utf8&useSSL=false
        slave_1:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dev2?characterEncoding=utf8&useSSL=false
        slave_2:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dev3?characterEncoding=utf8&useSSL=false
      primary: master

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #指定mapper.xml路径
  global-config:
    db-config:
      id-type: auto #全局默认主键类型设置为自增
  configuration:
    auto-mapping-behavior: partial #只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true #开启自动驼峰命名规则映射
